name: scanvault_premium
description: A premium document scanner app
publish_to: 'none'
version: 1.3.0+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Camera & Image Processing
  camera: ^0.10.5+5
  image: ^4.1.3
  image_picker: ^1.0.4
  cunning_document_scanner: ^1.2.2
  
  # PDF
  pdf: ^3.10.7
  flutter_pdfview: ^1.3.2
  
  # Storage & File Management
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  open_file: ^3.3.2
  
  # OCR & ML
  google_mlkit_text_recognition: ^0.11.0
  
  # Sharing & URLs
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  
  # In-App Purchases & Reviews
  in_app_purchase: ^3.1.11
  in_app_review: ^2.0.9
  
  # Permissions
  permission_handler: ^11.0.1
  
  # App Info
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true