name: doc_scanner_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  image: ^4.3.0
  pdf: ^3.11.1
  printing: ^5.13.4
  open_file: ^3.5.9
  cunning_document_scanner: ^1.2.3
  vector_math: ^2.1.4
  share_plus: ^10.1.2
  flutter_pdfview: ^1.3.2
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
