name: scanvault_freemium
description: A premium document scanner app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Camera & Image Processing
  camera: ^0.11.2+1
  image: ^4.1.3
  image_picker: ^1.0.4
  cunning_document_scanner: ^1.2.2
  
  # PDF
  pdf: ^3.10.7
  flutter_pdfview: ^1.3.2
  
  # Storage & File Management
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  open_file: ^3.3.2
  
  # OCR & ML
  google_mlkit_text_recognition: ^0.15.0
  
  # Sharing & URLs
  share_plus: ^12.0.1
  url_launcher: ^6.3.0
  
  # In-App Purchases & Reviews
  # in_app_purchase: ^3.2.0  # TODO: Re-enable when ready for payment integration
  in_app_review: ^2.0.9
  
  # Permissions
  permission_handler: ^12.0.1
  # Ads
  google_mobile_ads: ^5.2.0
  
  # App Info
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true


flutter_launcher_icons:
  ios: true
  android: false
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
